# Этот файл должен лежать в КОРНЕ проекта!

services:
  # Сервис для PHP и Nginx
  web:
    build:
      context: ./docker/php # Правильный путь к папке с Dockerfile
    container_name: gamedev_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html # Правильный путь к исходникам
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db

  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:13
    container_name: gamedev_db
    restart: always
    environment:
      # Используем переменные из .env файла
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: