# Финальная, рабочая конфигурация

services:
  # 1. Сервис для PHP
  php:
    build:
      context: ./docker/php  # Указываем путь к нашему Dockerfile
    container_name: gamedev_php
    volumes:
      - ./src:/var/www/html # Синхронизируем наш код с папкой внутри контейнера
    depends_on:
      - db

  # 2. Сервис для веб-сервера Nginx
  nginx:
    image: nginx:1.25-alpine # Используем официальный, легкий образ Nginx
    container_name: gamedev_nginx
    ports:
      - "8080:80" # Пробрасываем порт 8080 на наш компьютер
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf # Подключаем нашу конфигурацию для Nginx
    depends_on:
      - php # Говорим, что Nginx зависит от PHP

  # 3. Сервис для базы данных PostgreSQL
  db:
    image: postgres:13 # Используем официальный образ PostgreSQL
    container_name: gamedev_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: